### ISSUE TITLE
featuer de-correlation formula

### ISSUE THREAD

**Issue by plastar** [U-rara/AFDGCF#1]
Dear Author,
I am very interested in the novel paper ,but there are a question about the equation (20). Is the formula defined by column matrix P_C instead of P_R?
Thank you for your valuable time.

**Comment by U-rara** [comment]
Thank you very much for your interest in our work, and we commend your attention to detail. As you rightly pointed out, we confused P_R with P_C in Equation 20 and in the subsequent equations. We will correct this issue in the camera-ready version as well as in the subsequent arXiv version. We thank you again for pointing out this critical yet naive mistake before we submit the camera-ready version. At the same time, we appreciate your valuable time.
