### ISSUE TITLE
ValueError: File dataset\yelp-2018\yelp-2018.inter not exist.

### ISSUE THREAD

**Issue by Gshanyoufushuxianshen** [U-rara/AFDGCF#2]
1.Bug
运行main文件时发生这样的报错——“ValueError: File dataset\yelp-2018\yelp-2018.inter not exist.”
2.复现过程
![Snipaste_2024-06-30_08-54-04](https://github.com/U-rara/AFDGCF/assets/134292022/84200828-7dde-4725-934f-547af48a94d7)
图片是源代码的组织架构，开始是没有yelp-2018这个数据库的，第一次运行自动下载后成了图片中的结构。再次运行就出现了“ValueError: File dataset\yelp-2018\yelp-2018.inter not exist.”的报错。
3.以下是yaml的代码，我尝试用gpt修正，但还是不起效果，下面是gpt修正后的：
dataset: yelp-2018
data_path: dataset/yelp-2018
load_col:
  inter: [user_id, item_id, rating]
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
user_inter_num_interval: "[15,inf)"
item_inter_num_interval: "[15,inf)"
val_interval:
  rating: "[3,inf)"
4.我是一名大二本科生，这是我接触的第一次论文训练。论文我认为写的非常好，层次感强，逻辑严密。论文基本思想我已经基本把握。现在在复现代码的阶段，这个报错一直无法解决。你的举手之劳将会对一位本科生的科研之路带来巨大影响。

**Comment by Gshanyoufushuxianshen** [comment]
亲爱的作者，十分抱歉，我必须得承认：是自己的不细致导致了这个所谓的报错，这个问题在过去困扰了我几天。刚刚的情况仅仅是“yelp-2018"中的”-“被我忽略了。就在刚刚已经解决了这个问题，涉足一个全新的科研领域，新手的我显得局促不安。虽然现在代码运行又出现了新的错误，我正在努力解决。如果可以，请给这段代码的运行提供一些建议说明或者demo，让新手在理解代码方面有更少的障碍，我知道这个请求可能有点唐突。再次抱歉提了这么幼稚的issue.

**Comment by goalfur** [comment]
我现在也在复现这个代码，但是好像是wandb 出现问题了也不知道为什么？请问你有复现成功吗
